
import './theme-config.css'
import './globals.css';
import "@repo/ui/styles.css";
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import {Theme, ThemePanel} from '@radix-ui/themes'
import Navbar from './ui/Navbar'

const inter = Inter({ 
  subsets: ['latin'],
  variable: '--font-inter'
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
     
    <body className={inter.variable}>{children}</body>
 
      </html>
  )
}
